"""[FR-07] Alembic environment configuration.

Runs migrations against the database URL configured by the alembic
``Config`` (typically the in-process ``Config`` built per-test). The
SQLAlchemy URL is read from ``alembic_config.get_main_option(
"sqlalchemy.url")`` so per-test fixtures can point migrations at a
per-test SQLite file (SPEC.md line 256 — no in-memory mocks for FR-07).

Standard Alembic template; no business logic here. Each revision file
in ``migrations/versions/`` declares its own ``upgrade`` / ``downgrade``
operations.

Citations:
- SPEC.md line 130 — Alembic 三步真實演進 + 含資料搬遷 + downgrade 可逆.
- SPEC.md line 256 — FR-07 round-trip MUST run against a real SQLite
  file (not in-memory mock).
- Alembic documentation — ``env.py`` template for offline/online modes.
"""  # NFR-11
from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# this is the Alembic Config object, which provides access to the
# values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Target metadata is not used — every migration script is hand-written
# against explicit ``op.create_table`` / ``op.drop_table`` calls, not
# autogenerated from a SQLAlchemy declarative base. This keeps the
# downgrade path explicit and reviewable (SPEC.md line 142 — no DROP
# shortcuts).
target_metadata = None


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    Emits SQL to stdout without connecting to a database. Used by
    AC-7.7 (``test_migration_offline_sql_generation_matches_expectations``)
    to verify migration DDL without touching a live database.
    """  # NFR-09
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode against a live database engine.

    The engine is built from the alembic ``Config`` so per-test
    fixtures can point migrations at a per-test SQLite file. The
    ``pool.NullPool`` prevents connection-pooling surprises on the
    per-test file (SPEC.md line 256).
    """  # NFR-10
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()